apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: ceph-web
provisioner: kubernetes.io/rbd
parameters:
  monitors: 10.0.77.17,10.0.77.18,10.0.77.19
  adminId: admin
  adminSecretName: ceph-secret
  adminSecretNamespace: sonar
  pool: rbd
  userId: admin
  userSecretName: ceph-secret
