- name: Kernel Configuration
  hosts: all
  become: yes

  tasks:
    - name: load nf_conntrack_ipv4 module
      modprobe:
        name: nf_conntrack_ipv4
        state: present


    - name: load network bridges module
      modprobe:
        name: br_netfilter
        state: present

    - name: load ip_vs module
      modprobe:
        name: ip_vs
        state: present

    - name: load ip_vs_rr module
      modprobe:
        name: ip_vs_rr
        state: present

    - name: load ip_vs_wrr module
      modprobe:
        name: ip_vs_wrr
        state: present

    - name: load ip_vs_sh module
      modprobe:
        name: ip_vs_sh
        state: present

    - name: load ipip module
      modprobe:
        name: ipip
        state: present

    - name: load modules after reboot
      blockinfile:
        dest: /etc/modules
        block: |
          ip_vs
          ip_vs_rr
          ip_vs_wrr
          ip_vs_sh
          nf_conntrack_ipv4
          br_netfilter
          ipip
        backup: yes

    - name: adjust kernel parameters
      blockinfile:
        dest: /etc/sysctl.d/k8s.conf
        block: |
          net.ipv4.ip_forward=1
          net.ipv6.conf.all.disable_ipv6=1
          net.bridge.bridge-nf-call-iptables=1
          net.bridge.bridge-nf-call-ip6tables=1
          net.netfilter.nf_conntrack_max=2310720
          vm.overcommit_memory=1
          vm.panic_on_oom=0
          vm.swappiness=0
          fs.inotify.max_user_watches=89100
          fs.file-max=52706963
          fs.nr_open=52706963
        create: yes
        validate: /sbin/sysctl -p %s
