apiVersion: v1
kind: Service
metadata:
  name: "{{ template "db.tidb.fullname" . }}"
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
    app: "{{ template "db.tidb.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.tidb.service.type }}
  ports:
  - port: {{ .Values.tidb.service.mysql }}
    name:  mysql
  - port: {{ .Values.tidb.service.status }}
    name: status
  selector:
    component: "{{ template "db.tidb.fullname" . }}"
